// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: newService.proto

package grpc.newService;

public interface containsStringOrBuilder extends
    // @@protoc_insertion_point(interface_extends:containsString)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *int32 myInt = 2; //specify the exactly bits there are in the integer
   *bool myBool = 3;
   *bytes myImage = 4;
   * </pre>
   *
   * <code>string firstString = 10;</code>
   */
  java.lang.String getFirstString();
  /**
   * <pre>
   *int32 myInt = 2; //specify the exactly bits there are in the integer
   *bool myBool = 3;
   *bytes myImage = 4;
   * </pre>
   *
   * <code>string firstString = 10;</code>
   */
  com.google.protobuf.ByteString
      getFirstStringBytes();
}
