// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: newService.proto

package grpc.newService;

public interface newResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:newResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 firstInt = 1;</code>
   */
  int getFirstInt();
}
